---
title: "Fiji ER Report"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes: \usepackage{caption}
params:
  file_format: html
always_allow_html: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache=TRUE,
                      message=FALSE, warning=FALSE)


library(rlang)
library(dplyr)
library(kableExtra)
library(FijiNFMSCalculations)
if (!exists("fileFormat")) fileFormat <- params$file_format
getOption("max.print")
```

\captionsetup[table]{labelformat=empty}



# Monitoring Period yearly chart of accounts FRL and Monitored Em/Rems
```{r echo = FALSE}
options(max.print=1000000)

mp_yearly <- 
  cbind(
    t(rbind(as.data.frame(EmRems_Values$year1),as.data.frame(EmRems_Values$year2))),
    as.data.frame(replicate(3, rep.int(0,22))))
  
mp_yearly <- mp_yearly[order(row.names(mp_yearly)),]
      
names(mp_yearly) <- c(2019:2023)



overall_frl <- rbind( 
  ErpaYearlyFRL$erpa_yearly$yearly[2:6],
  mp_yearly[1:5]
)


row.names(overall_frl) <- NULL

overall_frl <- cbind(
  data.frame(value = c(t(ErpaYearlyFRL$erpa_yearly$yearly[1]), row.names(mp_yearly))),
  overall_frl
)

row.names(overall_frl) <- NULL
t <- overall_frl
t %>% 
  kable(fileFormat, caption = "Monitoring Period FRL and Monitored values",  
        format.args = list(big.mark = ",", digits= 4, nsmall = 4)) %>%
  
  kable_styling(
    latex_options = c("hold_position", "scale_down")
  )


```
# Year Monitoring Period Results Tables
## Year 1
```{r echo = FALSE}
t <- ResultsTables$year1
t %>% 
  kable(fileFormat, caption = "Monitoring Period values: year 1",
        format.args = list(big.mark = ",", digits= 4, nsmall = 4)) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down")
  )

```

## Year 2
```{r echo = FALSE}
t <- ResultsTables$year2
t %>% 
  kable(fileFormat, caption = "Monitoring Period values: year 2",
        format.args = list(big.mark = ",", digits= 4, nsmall = 4)) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down")
  )

```

# Table of Parameters and uncertainty
```{r echo = FALSE}
ParameterTable <- data.frame(
  symbol = character(),
  name = character(), 
  value = numeric(), 
  LCI = numeric(), 
  UCI=numeric(), 
  error = numeric(),
  model=character(),
  stringsAsFactors=FALSE)

ParameterTable <- rbind(ParameterTable, list(
  symbol = "\\begin{align} EF_{Def,upland} \\end{align}",
  name = "EFDeforUp", 
  value = EFDeforUp, 
  LCI = EFDeforUp_LCI, 
  UCI= EFDeforUp_UCI, 
  error = NA,
  model="Triangle"),
  stringsAsFactors=FALSE)


ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} EF_{Def,lowland} \\end{align}",
  name  = "EFDeforLow",
  value = EFDeforLow,
  LCI   = EFDeforLow_LCI,
  UCI   = EFDeforLow_UCI,
  error    = NA,
  model ="Triangle"
), stringsAsFactors=FALSE)

 ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} TEF \\end{align}",
  name  = "TEF",
  value = TEF,
  LCI   = TEF - TEF * errTEF,
  UCI   = TEF + TEF * errTEF,
  error    = errTEF,
  model ="Triangle"
), stringsAsFactors=FALSE)


ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} MAIB_{SW} \\end{align}",
  name  = "MAIBsw",
  value = MAIBsw,
  LCI   = MAIBsw - MAIBsw * errMAIBsw,
  UCI   = MAIBsw + MAIBsw * errMAIBsw,
  error    = errMAIBsw,
  model ="Triangle"
), stringsAsFactors=FALSE)


ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} \\Delta ABG_{NFF} \\end{align}",
  name  = "EFNFDeg",
  value = EFNFDeg,
  LCI   = EFNFDeg_LCI,
  UCI   = EFNFDeg_UCI,
  error    = NA,
  model ="Triangle"
), stringsAsFactors=FALSE)

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} MAIC_{FD} \\end{align}",
  name  = "MAICFell",
  value = MAICFell,
  LCI   = MAICFell - MAICFell * ErrMAICFell,
  UCI   = MAICFell + MAICFell * ErrMAICFell,
  error    = ErrMAICFell,
  model ="Triangle"
), stringsAsFactors=FALSE)


ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} MAIV_{AR} \\end{align}",
  name  = "MAIVar",
  value = MAIVar,
  LCI   = MAIVar - (MAIVar * errMAIVar),
  UCI   = MAIVar + (MAIVar * errMAIVar),
  error    = errMAIVar,
  model ="Triangle"
), stringsAsFactors=FALSE)


ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} \\overline{MAIV}_{HW} \\end{align}",
  name  = "MAIVhw",
  value = MAIVhw,
  LCI   = MAIVhw - MAIVhw * errMAIVhw,
  UCI   = MAIVhw + MAIVhw * errMAIVhw,
  error = errMAIVhw,
  model ="Triangle"
), stringsAsFactors=FALSE)

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} BCEF_{AR,I} \\end{align}",
  name  = "BiomassConvExpansionARefor",
  value = BiomassConvExpansionARefor,
  LCI   = BiomassConvExpansionARefor - (BiomassConvExpansionARefor * errBiomassConvExpansionARefor),
  UCI   = BiomassConvExpansionARefor + (BiomassConvExpansionARefor * errBiomassConvExpansionARefor),
  error = errBiomassConvExpansionARefor,
  model ="Triangle"
), stringsAsFactors=FALSE)

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} BCEF_{HW,R} \\end{align}",
  name  = "BiomassConvExpansionHW",
  value = BiomassConvExpansionHW,
  LCI   = BiomassConvExpansionHW - BiomassConvExpansionHW * errBiomassConvExpansionHW,
  UCI   = BiomassConvExpansionHW + BiomassConvExpansionHW * errBiomassConvExpansionHW,
  error = errBiomassConvExpansionHW,
  model ="Triangle"
), stringsAsFactors=FALSE)

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} BCEF_{HW,I} \\end{align}",
  name  = "BiomassConvExpansionIncHW",
  value = BiomassConvExpansionIncHW,
  LCI   = BiomassConvExpansionIncHW - BiomassConvExpansionIncHW * errBiomassConvExpansionIncHW,
  UCI   = BiomassConvExpansionIncHW + BiomassConvExpansionIncHW * errBiomassConvExpansionIncHW,
  error = errBiomassConvExpansionIncHW,
  model ="Triangle"
), stringsAsFactors=FALSE)

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} R_{wl} \\end{align}",
  name  = "RootToShootTropRain",
  value = RootToShootTropRain,
  LCI   = RootToShootTropRain - (RootToShootTropRain * errRootToShootTropRain),
  UCI   = RootToShootTropRain + (RootToShootTropRain * errRootToShootTropRain),
  error = errRootToShootTropRain,
  model ="Triangle"
), stringsAsFactors=FALSE)    

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} R_{dll} \\end{align}",
  name  = "RootToShootDryLandSmall",
  value = RootToShootDryLandSmall,
  LCI   = errLowerRtSDryLandSmall,
  UCI   = errUpperRtSDryLandSmall,
  error = NA,
  model ="Triangle"
), stringsAsFactors=FALSE)    

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} R_{dlh} \\end{align}",
  name  = "RootToShootDryLandBig",
  value = RootToShootDryLandBig,
  LCI   = errLowerRtSDryLandBig,
  UCI   = errUpperRtSDryLandBig,
  error = NA,
  model ="Triangle"
), stringsAsFactors=FALSE)    

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} \\lambda_{Pine} \\end{align}",
  name  = "RecoveryRateSW",
  value = RecoveryRateSW,
  LCI = qnorm(p = c(QLCI), mean = RecoveryRateSW, sd = (RecoveryRateSW * errRecoveryRateSW)),
  UCI = qnorm(p = c(QUCI), mean = RecoveryRateSW, sd = (RecoveryRateSW * errRecoveryRateSW)),
  error = errRecoveryRateSW,
  model ="Norm"
), stringsAsFactors=FALSE)    

ParameterTable <- rbind(ParameterTable,list(
  symbol = "\\begin{align} \\rho_{Pine} \\end{align}",
  name  = "WoodDensitySW",
  value = WoodDensitySW,
  LCI = qnorm(p = c(QLCI), mean = WoodDensitySW, sd = SDWoodDensitySW),
  UCI = qnorm(p = c(QUCI), mean = WoodDensitySW, sd = SDWoodDensitySW),
  error = NA,
  model ="Norm"
), stringsAsFactors=FALSE)  
    
ParameterTable %>% 
  kable(fileFormat, caption = "Parameter and associated uncertainty",
        format.args = list(big.mark = ",", digits= 4, nsmall = 4)) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down")
  )
     
```
    
# Table of Monitoring Report Parameters 
```{r echo = FALSE}


data.frame(value = unlist(MonitoringReportParams)) %>% 
  kable(fileFormat, caption = "Monitoring report parameters", 
        format.args = list(big.mark = ",",digits=2, nsmall = 0,scientific = FALSE)) %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down")
  )
     
```

# Table of Monitored Values
```{r echo = FALSE}
MVTable <- data.frame(
  symbol = character(),
  name = character(),
  year = character(),
  value = numeric(), 
  LCI = numeric(), 
  UCI=numeric(), 
  error = numeric(),
  model=character(),
  stringsAsFactors=FALSE)

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPDF,Lowland} \\end{align}",
  name  = "DeforAreaLow",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$DeforAreaLow,
  LCI = unname(quantile(MonitoredValues$year1$McDeforAreaLow,probs=QLCI)),
  UCI = unname(quantile(MonitoredValues$year1$McDeforAreaLow,probs=QUCI)),
  error = NA,
  model ="Sampled"
), stringsAsFactors=FALSE)  
    

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPDF,Upland} \\end{align}",
  name  = "DeforAreaUp",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$DeforAreaUp,
  LCI = unname(quantile(MonitoredValues$year1$McDeforAreaUp,probs=QLCI)),
  UCI = unname(quantile(MonitoredValues$year1$McDeforAreaUp,probs=QUCI)),
  error = NA,
  model ="Sampled"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPAR,t} \\end{align}",
  name  = "AReforArea",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$AReforArea$area_ha[1],
  LCI = unname(quantile(MonitoredValues$year1$McAReforArea,probs=QLCI)),
  UCI = unname(quantile(MonitoredValues$year1$McAReforArea,probs=QUCI)),
  error = NA,
  model ="Sampled"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPFD,t} \\end{align}",
  name  = "FDegFellArea",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$FDegFellArea$area_ha,
  LCI = MonitoredValues$year1$FDegFellArea$area_ha - MonitoredValues$year1$FDegFellArea$area_ha * ErrAreaFell,
  UCI = MonitoredValues$year1$FDegFellArea$area_ha + MonitoredValues$year1$FDegFellArea$area_ha * ErrAreaFell,
  error = ErrAreaFell,
  model ="Triangle"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPHWPlant,t} \\end{align}",
  name  = "FPlnAreaPlantHwd",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$FPlnAreaPlantHwd$area_ha,
  LCI = MonitoredValues$year1$FPlnAreaPlantHwd$area_ha - MonitoredValues$year1$FPlnAreaPlantHwd$area_ha * ErrAreaARefor,
  UCI = MonitoredValues$year1$FPlnAreaPlantHwd$area_ha + MonitoredValues$year1$FPlnAreaPlantHwd$area_ha * ErrAreaARefor,
  error = ErrAreaARefor,
  model ="Triangle"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPSWPlant,t} \\end{align}",
  name  = "FPlnAreaPlantSwd",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$FPlnAreaPlantSwd$area_ha,
  LCI = MonitoredValues$year1$FPlnAreaPlantSwd$area_ha - MonitoredValues$year1$FPlnAreaPlantSwd$area_ha * ErrAreaARefor,
  UCI = MonitoredValues$year1$FPlnAreaPlantSwd$area_ha + MonitoredValues$year1$FPlnAreaPlantSwd$area_ha * ErrAreaARefor,
  error = ErrAreaARefor,
  model ="Triangle"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPNFF,t} \\end{align}",
  name  = "NFDegArea",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$NFDegArea,
  LCI = MonitoredValues$year1$NFDegArea_LCI,
  UCI = MonitoredValues$year1$NFDegArea_UCI,
  error = NA,
  model ="Triangle"
), stringsAsFactors=FALSE) 

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} V_{MPNF,t} \\end{align}",
  name  = "FDegFellVol",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$FDegFellVol,
  LCI = NA,
  UCI = NA,
  error = NA,
  model = NA
), stringsAsFactors=FALSE) 

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} V_{MPHWHarvest,t} \\end{align}",
  name  = "FPlnVolHarvHwd",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$FPlnVolHarvHwd,
  LCI = NA,
  UCI = NA,
  error = NA,
  model = NA
), stringsAsFactors=FALSE) 

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} V_{MPSWHarvest,t} \\end{align}",
  name  = "FPlnVolHarvSwd",
  year = as.character(MonitoredValues$year1$year),
  value = MonitoredValues$year1$FPlnVolHarvSwd,
  LCI = NA,
  UCI = NA,
  error = NA,
  model = NA
), stringsAsFactors=FALSE) 


MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPDF,Lowland} \\end{align}",
  name  = "DeforAreaLow",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$DeforAreaLow,
  LCI = unname(quantile(MonitoredValues$year2$McDeforAreaLow,probs=QLCI)),
  UCI = unname(quantile(MonitoredValues$year2$McDeforAreaLow,probs=QUCI)),
  error = NA,
  model ="Sampled"
), stringsAsFactors=FALSE)  
    

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPDF,Upland} \\end{align}",
  name  = "DeforAreaUp",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$DeforAreaUp,
  LCI = unname(quantile(MonitoredValues$year2$McDeforAreaUp,probs=QLCI)),
  UCI = unname(quantile(MonitoredValues$year2$McDeforAreaUp,probs=QUCI)),
  error = NA,
  model ="Sampled"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPAR,t} \\end{align}",
  name  = "AReforArea",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$AReforArea$area_ha[1],
  LCI = unname(quantile(MonitoredValues$year2$McAReforArea,probs=QLCI)),
  UCI = unname(quantile(MonitoredValues$year2$McAReforArea,probs=QUCI)),
  error = NA,
  model ="Sampled"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPFD,t} \\end{align}",
  name  = "FDegFellArea",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$FDegFellArea$area_ha[2],
  LCI = MonitoredValues$year2$FDegFellArea$area_ha[2] - MonitoredValues$year2$FDegFellArea$area_ha[2] * ErrAreaFell,
  UCI = MonitoredValues$year2$FDegFellArea$area_ha[2] + MonitoredValues$year2$FDegFellArea$area_ha[2] * ErrAreaFell,
  error = ErrAreaFell,
  model ="Triangle"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPHWPlant,t} \\end{align}",
  name  = "FPlnAreaPlantHwd",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$FPlnAreaPlantHwd$area_ha[2],
  LCI = MonitoredValues$year2$FPlnAreaPlantHwd$area_ha[2] - MonitoredValues$year2$FPlnAreaPlantHwd$area_ha[2] * ErrAreaARefor,
  UCI = MonitoredValues$year2$FPlnAreaPlantHwd$area_ha[2] + MonitoredValues$year2$FPlnAreaPlantHwd$area_ha[2] * ErrAreaARefor,
  error = ErrAreaARefor,
  model ="Triangle"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPSWPlant,t} \\end{align}",
  name  = "FPlnAreaPlantSwd",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$FPlnAreaPlantSwd$area_ha[2],
  LCI = MonitoredValues$year2$FPlnAreaPlantSwd$area_ha[2] - MonitoredValues$year2$FPlnAreaPlantSwd$area_ha[2] * ErrAreaARefor,
  UCI = MonitoredValues$year2$FPlnAreaPlantSwd$area_ha[2] + MonitoredValues$year2$FPlnAreaPlantSwd$area_ha[2] * ErrAreaARefor,
  error = ErrAreaARefor,
  model ="Triangle"
), stringsAsFactors=FALSE)  

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} A_{MPNFF,t} \\end{align}",
  name  = "NFDegArea",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$NFDegArea,
  LCI = MonitoredValues$year2$NFDegArea_LCI,
  UCI = MonitoredValues$year2$NFDegArea_UCI,
  error = NA,
  model ="Triangle"
), stringsAsFactors=FALSE) 


## New values no UC

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} V_{MPNF,t} \\end{align}",
  name  = "FDegFellVol",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$FDegFellVol,
  LCI = NA,
  UCI = NA,
  error = NA,
  model = NA
), stringsAsFactors=FALSE) 

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} V_{MPHWHarvest,t} \\end{align}",
  name  = "FPlnVolHarvHwd",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$FPlnVolHarvHwd,
  LCI = NA,
  UCI = NA,
  error = NA,
  model = NA
), stringsAsFactors=FALSE) 

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} V_{MPSWHarvest,t} \\end{align}",
  name  = "FPlnVolHarvSwd",
  year = as.character(MonitoredValues$year2$year),
  value = MonitoredValues$year2$FPlnVolHarvSwd,
  LCI = NA,
  UCI = NA,
  error = NA,
  model = NA
), stringsAsFactors=FALSE) 

MVTable <- rbind(MVTable,list(
  symbol = "\\begin{align} \\Lambda_{MPSWBurn,t} \\end{align}",
  name  = "FDegBurnData",
  year = NA,
  value = NA,
  LCI = NA,
  UCI = NA,
  error = NA,
  model ="Census"
), stringsAsFactors=FALSE) 



f <- function(x) {
  y <- as.character(format(x,big.mark = ",",digits= 2, nsmall = 2,scientific=F))
  return(replace(y,are_na(x)," "))
}



MVTable %>% 
  mutate(across(where(~ is.numeric(.x)), ~ f(.x)))%>% 
  kable(fileFormat, escape=FALSE, caption = "Monitored Values and associated uncertainty") %>%
  kable_styling(
    latex_options = c("hold_position", "scale_down")
  )
     
```

