---
title: "Fiji NFMS ER Calculations Summary"  
author: "David Chambers, Carly Green, Michael Green"   
date: "May 2021"
output: 
  html_document:
    toc: true
    toc_depth: 5
    toc_float: 
      collapsed: false
      smooth_scroll: true
      
---
# 1. Introduction

## 1.1 Purpose of Document 

This document describes the methodology used to calculate the emissions, removals and emissions reductions in R for the for the Fijian Ministry of Forestry Forest Carbon Partnership Fund (FCPF) Monitoring Report.

The document will: \
 - Outline the parameters and outputs for the functions used to calculate the emissions and removals from REDD+ Activities,   
 - Reference the functions used to calculate the outputs required for the FCPF monitoring report,\
 - Discuss the outputs from the R calculations with reference to their values, associated uncertainty and sensitivity analysis,\
 - Provide guidance on modification of the code for a change in methodology or adoption to a new data set (e.g a new country),\
 - Provide information/code for the packages used to complete the calculations.     

## 1.2 Terminology 

Code Naming Convention

Root  Calculation Type
----- ----------  -------
Calc  Est         Em
Mp    Net         Rem
Rp    Gross       EmRems
                  ERs
                  
Calc:   Calculation \
Mp:     Monitoring Period \
Rp:     Reporting Period \
Est:    Estimate \
Em:     Emissions (always +ve value, CO~2~e emitted to atmosphere) \
Rem:    Removal (always -ve value, CO~2~e removed from atmosphere) \
EmRem:  Emissions and Removals - can be +ve or -ve as it is considers both emissions and removals from an activity.  \ 
ERs:    Emission Reductions 


## Preliminaries 

Ask MG

Download library?  
Packages?  
Versions?  

### Acronyms 

[Check with MG]





# 2.	R Script Calculations	

This section describes the calculations carried out by the R Script to produce the required values from the FCPF Monitoring Report. 


## 2.1.	REDD+ Activities Annual Estimations	

The REDD+ Activities note the contribution of emissions and removals from Deforestation, Forest Degradation and Enhancements. 

### 2.1.1.	Deforestation	

**Scope**
Estimates emissions from deforestation from lowland and upland natural forest, excluding areas subject to logging, in Fiji. 

**Reference**

Package - `FijiNFMSCalculations`  
Function Script - `Deforestation.R`  

**Prior Requirements**

TBC
Data: Hectares of Area Deforested in lowland an upland natural forest. 

**Output**

This emission source provides a contribution to the overall emissions from Forest and Forestry related activities in Fiji in tCO~2~e. This value is required for reporting and further calculation of values in the FCPF Monitoring Report.

**TEST**
Include this?
`test-CalcEMDF.R`

### 2.1.2.	Forest Degradation	

Emissions from degradation are estimated as the combination of the net emissions/removals from logging in Natural Forests and the emissions from Fire in Pine Plantations.

#### Felling	

**Scope**
Emissions related to logging practices in natural forests. 

**Reference**

Package - `FijiNFMSCalculations`  
Function Script - `Felling.R`  

**Prior Requirements**

Data?

**Output**

This emissions source provides a contribution to the overall emissions from Forest and Forestry related activities in Fiji. This value is required for reporting and further calculation of values in the FCPF Monitoring Report.


#### Emissions from Fire	

**Scope**
Emissions from fire in Softwood Plantations (Pine)

**Reference**

Package - `FijiNFMSCalculations`  
Function Script - `Burning.R`  

**Prior Requirements**

Data?

**Output**

This emissions source provides a contribution to the overall emissions from Forest and Forestry related activities in Fiji. This value is required for reporting and further calculation of values in the FCPF Monitoring Report.


### 2.1.3.	Enhancements

Enhancements are the removals in tCO~2~e related to afforestation and forest plantations in Fiji. 

#### Afforestation	

**Scope**
Removals in tCO~2~e from Afforestation/Reforestation activities - defined as the conversion of land in the land-use sub category Non-Forest to land in the sub-category Natural Forest(Low-or Upland) and Plantations (Softwood and Hardwood). 

**Reference**

Package - `FijiNFMSCalculations`  
Function Script - `Afforestation.R`  

**Prior Requirements**

Data?

**Output**

This removals source provides a contribution to the overall emissions/removals from Forest and Forestry related activities in Fiji. This value is required for reporting and further calculation of values in the FCPF Monitoring Report.

#### Forest Plantations	

**Scope**
Emissions and Removals in tCO~2~e from Forest Plantation Management. This includes the growth and harvesting of Softwood and Hardwood plantation stocks. 

**Reference**

Package - `FijiNFMSCalculations`  
Function Script - `ForestPlantations.R`  

**Prior Requirements**

Data?

**Output**

This emissions/removals source provides a contribution to the overall emissions/removals from Forest and Forestry related activities in Fiji. This value is required for reporting and further calculation of values in the FCPF Monitoring Report.


### 2.1.4.	Annual Net Emissions/Removals from REDD+ Activities	

**Scope**
The summation of the annual net emissions or removals from the REDD+ activities: Deforestation, Forest Degradation and Enhancements.   

**Reference**

Package - ``  
Function Script - `TBC` `Fiji_ER_Estimates.R`  

**Prior Requirements**

Calculation of all REDD+ activities (Deforestation, Forest Degradation, Enhancements)

**Output**

The values of net emissions and removals are reported in the FCPF Monitoring Report and are used to calculate Emissions Reductions against the Forest Reference Level (FRL)


## 2.2.	Emission Reductions	

**Scope**
The Emissions Reductions are calculated by subtracting the annual net emissions from the Forest Reference Level (FRL)

**Reference**

Package - `FijiNFMSCalculations`  
Function Script - `ForestPlantations.R`  

**Prior Requirements**

Forest Reference Level (FRL) from Fiji Ministry of Forestry 
Net Emissions/Removals value for the monitoring period.  

**Output**

The value of Emission Reductions is reported in the FCPF Monitoring Report. 


## 2.3.	Outputs for FCPF Monitoring Report	

**Scope**
The outputs from the R script calculation are used to populate the FCPF Monitoring report for the reporting period for Fiji. In particular tables 4.2, 4.3, 5.2.2, 7.2 and 8.

**Reference**

`TableCreationFunction.R`

**Prior Requirements**

Calculation of all REDD+ activities (Deforestation, Forest Degradation, Enhancements), Emissions Reductions and net emissions/removal values. 

**Output**

Values to be reported in the FCPF monitoring report including Tables 4.2, 4.3, 5.2.2, 7.2 and 8.

# 3.	Discussion

## 3.1.	Drivers	

### 3.1.1.	Values	

### 3.1.2.	Values with Uncertainty	

### 3.1.3.	Sensitivity Analysis	

## 3.2.	Modification of Code	

### 3.2.1.	Resulting from changes to Methodology	

### 3.2.2	Adoption of code for a new country context	

## 3.3.	Testing & Unit Testing

# 4.	Packages	{.tabset}

## Fiji NFMS Calculations	

https://cran.r-project.org/web/packages/roxygen2md/roxygen2md.pdf 

-	`Afforestation.R`
-	`Burning.R`
-	`CarbonConversion.R`
-	`Constants.R`
-	`Default_Parameters.R`
-	`Deforestation.R`
-	`EmissionReductions.R`
-	`ER_Calculated_Values.R`
-	`Felling.R`
-	`Fiji_Constants_from_Reference_Level.R`
-	`Fiji_Specific_Parameters.R`
-	`ForestPlantations.R`
-	`FRL_Calculated_Values.R`
-	`ReportTotals.R`
-	`utils-pipe.R`




## Value with Uncertainty	

-	`gen_sample.R`
-	`init.R`
-	`ops.R`
-	`summary.R`
-	`types.R`
-	`utils.R`
-	`utils-pipe.R`
-	`ValuesWithUncertainty.R`


## Monte Carlo Utils	

-	`ASCBRMonteCarloSamples.R`
-	`GenMonteCarloSamples.R`
-	`PlotMonteCarloSamples.R`
-	`StableMonteCarloSamples.R`
-	`utils-pipe.R`


## FCPF Monitoring Report Tables	

-	`TableCreationFunctions.R`



```{r} 
```
